### ISSUE TITLE
Let's write markdown

### ISSUE THREAD

**Issue by datascitest** [datascitest/datasciencecoursera#1]
# This is an h1
### code

``` python
def hello():
  print "hello"
```
# task this month
- [ ] finish the picture
- [ ] finish the tools
- [x] complete the voting function
